filrouge_admin_list:
    path: /
    defaults: {_controller:AppBundle:Default:admin}

filrouge_admin_add_skill:
    path: /skill/add
    defaults: {_controller:AppBundle:Skill:add }
    requirements:
        id: \d+
        
filrouge_admin_update_skill:
    path: /skill/update/{id}
    defaults: {_controller:AppBundle:Skill:update }
    requirements:
        id: \d+
        
filrouge_admin_remove_skill:
    path: /skill/remove/{id}
    defaults: {_controller:AppBundle:Skill:remove }
    requirements:
        id: \d+

filrouge_admin_add_category:
    path: /category/add
    defaults: {_controller:AppBundle:Category:add }
    requirements:
        id: \d+
        
filrouge_admin_update_category:
    path: /category/update/{id}
    defaults: {_controller:AppBundle:Category:update }
    requirements:
        id: \d+
        
filrouge_admin_remove_category:
    path: /category/remove/{id}
    defaults: {_controller:AppBundle:Category:remove }
    requirements:
        id: \d+
        
filrouge_admin_user_remove:
    path: /user/remove/{id}
    defaults: {_controller:AppBundle:User:remove }
    requirements:
        id: \d+
        
filrouge_admin_project_remove:
    path: /project/remove/{id}
    defaults: {_controller:AppBundle:Project:remove }
    requirements:
        id: \d+
        
filrouge_admin_user_importCsv:
    path: /user/importCsv
    defaults: {_controller:AppBundle:User:importCsv }
    methods: [POST]
