filrouge_project_list:
    path: /{page}
    defaults: {_controller:AppBundle:Project:list, page:1 }
    requirements:
        page: \d+
        
filrouge_project_search:
    path: /search
    defaults: {_controller:AppBundle:Project:search }
    methods: [POST]

filrouge_project_detail:
    path: /detail/{id}
    defaults: {_controller:AppBundle:Project:detail }
    requirements:
        id: \d+

filrouge_project_add:
    path: /add
    defaults: {_controller:AppBundle:Project:add}

filrouge_project_update:
    path: /update/{id}
    defaults: {_controller:AppBundle:Project:update }
    requirements:
        id: \d+
        
filrouge_project_apply:
    path: /detail/{id}/apply/{idProjectSkill}
    defaults: {_controller:AppBundle:Project:apply }
    requirements:
        id: \d+
        idProjectSkill: \d+
       
filrouge_project_accept:
    path: /update/{id}/accept/{idMember}
    defaults: {_controller:AppBundle:Project:accept }
    requirements:
        id: \d+
        idMember: \d+
        
filrouge_project_refuse:
    path: /update/{id}/refuse/{idMember}
    defaults: {_controller:AppBundle:Project:refuse }
    requirements:
        id: \d+
        idMember: \d+

filrouge_project_fire:
    path: /update/{id}/fire/{idMember}
    defaults: {_controller:AppBundle:Project:fire }
    requirements:
        id: \d+
        idMember: \d+
        
filrouge_project_addComment:
    path: /detail/{id}/addComment/{page}
    defaults: {_controller:AppBundle:Comment:add }
    requirements:
        id: \d+
        
filrouge_project_updateComment:
    path: /detail/{id}/updateComment/{page}/{idComment}
    defaults: {_controller:AppBundle:Comment:update }
    requirements:
        id: \d+
        idComment: \d+ 

filrouge_project_removeComment:
    path: /detail/{id}/removeComment/{page}/{idComment}
    defaults: {_controller:AppBundle:Comment:remove }
    requirements:
        id: \d+
        idComment: \d+ 
        
        