filrouge_project_list:
    path: /{page}
    defaults: {_controller:AppBundle:Project:list, page:1 }
    requirements:
        page: \d+

filrouge_project_detail:
    path: /detail/{id}
    defaults: {_controller:AppBundle:Project:detail, id:1 }
    requirements:
        id: \d+

filrouge_project_add:
    path: /add
    defaults: {_controller:AppBundle:Project:add}

filrouge_project_update:
    path: /update/{id}
    defaults: {_controller:AppBundle:Project:update, id:1 }
    requirements:
        id: \d+

filrouge_project_remove:
    path: /remove/{id}
    defaults: {_controller:AppBundle:Project:remove, id:1 }
    requirements:
        id: \d+
        
filrouge_project_apply:
    path: /detail/{id}/apply/{name}
    defaults: {_controller:AppBundle:Message:apply, id:1 }
    requirements:
        id: \d+
       
filrouge_project_response:
    path: /update/{id}/response
    defaults: {_controller:AppBundle:Message:response, id:1 }
    requirements:
        id: \d+