filrouge_project_list:
    path: /{page}
    defaults: {_controller:AppBundle:Project:list, page:1 }
    requirements:
        page: \d+
        
filrouge_project_search:
    path: /search
    defaults: {_controller:AppBundle:Project:search }
    methods: [POST]

filrouge_project_detail:
    path: /detail/{id}
    defaults: {_controller:AppBundle:Project:detail, id:1 }
    requirements:
        id: \d+

filrouge_project_add:
    path: /add
    defaults: {_controller:AppBundle:Project:add}

filrouge_project_update:
    path: /update/{id}
    defaults: {_controller:AppBundle:Project:update, id:1 }
    requirements:
        id: \d+
        
filrouge_project_apply:
    path: /detail/{id}/apply/{idProjectSkill}
    defaults: {_controller:AppBundle:Project:apply, id:1 }
    requirements:
        id: \d+
        idProjectSkill: \d+
       
filrouge_project_accept:
    path: /update/{id}/accept/{idMember}
    defaults: {_controller:AppBundle:Project:accept, id:1 }
    requirements:
        id: \d+
        idMember: \d+
        
filrouge_project_refuse:
    path: /update/{id}/refuse/{idMember}
    defaults: {_controller:AppBundle:Project:refuse, id:1 }
    requirements:
        id: \d+
        idMember: \d+