filrouge_homepage:
    path:     /{pageMP}/{page}
    defaults: { _controller: AppBundle:Default:index, pageMP:1 , page:1 }
    requirements:
        pageMP: \d+
        page: \d+
    
filrouge_user:
    resource: "@AppBundle/Resources/config/user.yml"
    prefix:   /user
    
filrouge_project:
    resource: "@AppBundle/Resources/config/project.yml"
    prefix:   /project

filrouge_admin:
    resource: "@AppBundle/Resources/config/admin.yml"
    prefix:   /admin
    
filrouge_message:
    path: /message
    defaults: {_controller: AppBundle:default:listMessage }
    
filrouge_notification:
    path: /notification
    defaults: {_controller: AppBundle:default:listNotification }
    
filrouge_generalCondition:
    path: /gc
    defaults: {_controller: AppBundle:default:generalCondition }
