filrouge_homepage:
    path:     /{pageMP}/{page}
    defaults: { _controller: AppBundle:Default:index, pageMP:1 , page:1 }
    requirements:
        pageMP: \d+
        page: \d+
    
filrouge_notification:
    path: /notification/{page}
    defaults: {_controller: AppBundle:Default:listNotification, page:1 }
    requirements:
        page: \d+
    
filrouge_generalCondition:
    path: /generalCondition
    defaults: {_controller: AppBundle:Default:generalCondition } 

filrouge_contactAdmin:
    path: /contactAdmin
    defaults: {_controller: AppBundle:Default:contactAdmin } 
    
filrouge_contactAdmin_send:
    path: /contactAdmin/{id}
    defaults: {_controller: AppBundle:Default:sendMailAdmin }
    requirements:
        page: \d+
    methods: [POST]
    
filrouge_user:
    resource: "@AppBundle/Resources/config/user.yml"
    prefix:   /user
    
filrouge_project:
    resource: "@AppBundle/Resources/config/project.yml"
    prefix:   /project

filrouge_admin:
    resource: "@AppBundle/Resources/config/admin.yml"
    prefix:   /admin
    
filrouge_message:
    resource: "@AppBundle/Resources/config/message.yml"
    prefix:   /message
