<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    //Récupérer un commentaire en particulier et le projet auquel il est lié
    public function findOneCommentEager($idComment) {
        return $this->createQueryBuilder('c')
                    ->addSelect('p')
                    ->LeftJoin('c.project', 'p')
                    ->where('c.id = :id')
                    ->orderBy('c.creationDate', 'DESC')
                    ->setParameter('id', $idComment)
                    ->getQuery()
                    ->getOneOrNullResult();    
    }
    
     //Récupérer tous les commentaires d'un article
    public function findAllCommentsEager($id) {
        return $this->createQueryBuilder('c')
                    ->addSelect('p')
                    ->LeftJoin('c.project', 'p')
                    ->where('p.id = :id')
                    ->orderBy('c.creationDate', 'DESC')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();    
    }
}
