<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    
    //Récupérer tous les messages triés par date
    public function findAllMessagesEager() {
        return $this->createQueryBuilder('m')
                    ->addSelect('m')
                    ->orderBy('m.creationDate', 'DESC')
                    ->getQuery()
                    ->getResult();
    }
}
