<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{  
    //Récupérer tous les 5 dernières notifications par date
    public function findLastNotificationsEager() {
        return $this->createQueryBuilder('n')
                    ->addSelect('n')
                    ->addSelect('p')
                    ->leftJoin('n.project', 'p')
                    ->orderBy('n.creationDate', 'DESC')
                    ->setMaxResults(5)
                    ->getQuery()
                    ->getResult();
    }
    
    //Récupérer toutes les notifications avec pagination
    public function findAllMessagesPageEager($page= 1, $maxPerPage = 20) {
        $query = $this->createQueryBuilder('n')
                    ->addSelect('n')
                    ->addSelect('p')
                    ->leftJoin('n.project', 'p')
                    ->orderBy('n.creationDate', 'DESC');
        $query->setFirstResult(($page-1)*$maxPerPage)
              ->setMaxResults($maxPerPage);
        return new Paginator($query);      
    }
}
