<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{  
    //Récupérer tous les messages avec le nom du manager, le projet
    public function findAllNotificationsEager() {
        return $this->createQueryBuilder('n')
                    ->addSelect('n')
                    ->addSelect('p')
                    ->leftJoin('n.project', 'p')
                    ->orderBy('n.creationDate', 'DESC')
                    ->getQuery()
                    ->getResult();
    }
}
