<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSkillRepository extends EntityRepository
{
    //Récupérer une compétence de projet avec son nom
    public function findOneProjectSkillEager($id) {
        return $this->createQueryBuilder('ps')
                    ->addSelect('s')
                    ->LeftJoin('ps.skill', 's')
                    ->where('ps.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
    
}
