<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    
    //Récupérer tous les projet avec le status et compétences
    //triés par date et pagination
    public function findAllPojectsPageEager($page= 1, $maxPerPage = 5) {
        $query = $this->createQueryBuilder('p')
                    ->addSelect('st')
                    ->addSelect('ps')
                    ->addSelect('sk')
                    ->LeftJoin('p.status', 'st')
                    ->LeftJoin('p.projectSkills', 'ps')
                    ->LeftJoin('ps.skill', 'sk')
                    ->orderBy('p.creationDate', 'DESC');
        $query->setFirstResult(($page-1)*$maxPerPage)
              ->setMaxResults($maxPerPage);
        return new Paginator($query);        
    }
    
    //Récupérer tous les projet d'un utilisateur
    //triés par date et pagination
    public function findAllPojectsByUserPageEager($page= 1, $maxPerPage = 5, $id) {
        $query = $this->createQueryBuilder('p')
                    ->addSelect('st')
                    ->addSelect('ps')
                    ->addSelect('sk')
                    ->addSelect('u')
                    ->LeftJoin('p.status', 'st')
                    ->LeftJoin('p.projectSkills', 'ps')
                    ->LeftJoin('ps.skill', 'sk')
                    ->LeftJoin('p.projectManager', 'u')
                    ->LeftJoin('p.projectMembers', 'up')
                    ->leftJoin('up.user', 'u')
                    ->where('u.id = :id')
                    ->setParameter('id', $id)
                    ->orderBy('p.creationDate', 'DESC');
        $query->setFirstResult(($page-1)*$maxPerPage)
              ->setMaxResults($maxPerPage);
        return new Paginator($query);        
    }
    
    //Récupérer tous les projet avec le status et compétences
    //triés par date
    public function findAllPojectsEager() {
        return $this->createQueryBuilder('p')
                    ->addSelect('st')
                    ->addSelect('ps')
                    ->addSelect('sk')
                    ->LeftJoin('p.status', 'st')
                    ->LeftJoin('p.projectSkills', 'ps')
                    ->LeftJoin('ps.skill', 'sk')
                    ->orderBy('p.creationDate', 'DESC')
                    ->getQuery()
                    ->getResult();       
    }
    
    //Récupérer tous les projet d'un utilisateur
    //triés par date
    public function findAllPojectsByUserEager($id) {
        return $this->createQueryBuilder('p')
                    ->addSelect('st')
                    ->addSelect('ps')
                    ->addSelect('sk')
                    ->addSelect('u')
                    ->addSelect('up')
                    ->addSelect('upu')
                    ->LeftJoin('p.status', 'st')
                    ->LeftJoin('p.projectSkills', 'ps')
                    ->LeftJoin('ps.skill', 'sk')
                    ->LeftJoin('p.projectManager', 'u')
                    ->LeftJoin('p.projectMembers', 'up')
                    ->leftJoin('up.user', 'upu')
                    ->where('u.id = :id')
                    ->orWhere('upu.id = :id')
                    ->setParameter('id', $id)
                    ->orderBy('p.creationDate', 'DESC')
                    ->getQuery()
                    ->getResult();    
    }
    
    //Récupérer un projet avec son status, ses étape...
    //son manager, ses membres et ses compétences recherchées
    public function findOneProjectEager($id) {
        return $this->createQueryBuilder('p')
                    ->addSelect('st')
                    ->addSelect('step')
                    ->addSelect('ststep')
                    ->addSelect('pm')
                    ->addSelect('m')
                    ->addSelect('u')
                    ->addSelect('ps')
                    ->addSelect('sk')
                    ->LeftJoin('p.status', 'st')
                    ->LeftJoin('p.steps', 'step')
                    ->LeftJoin('step.status', 'ststep')
                    ->LeftJoin('p.projectManager', 'pm')
                    ->LeftJoin('p.projectMembers', 'm')
                    ->LeftJoin('m.user', 'u')
                    ->LeftJoin('p.projectSkills', 'ps')
                    ->LeftJoin('ps.skill', 'sk')
                    ->where('p.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
