<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    //Récupérer une école en fonction de son nom d
    public function findOneSchoolEager($name) {
        return $this->createQueryBuilder('s')
                    ->where('s.name = :name')
                    ->setParameter('name', $name)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
