<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProjectRepository extends EntityRepository
{  
    //Récupérer tous les membres d'un projet avec leurs compétences
    //En fonction de l'ID UserProject
    public function findOneUserProjectEager($id) {
        return $this->createQueryBuilder('us')
                    ->addSelect('u')
                    ->addSelect('p')
                    ->LeftJoin('us.user', 'u')
                    ->LeftJoin('us.project', 'p')
                    ->where('us.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getOneOrNullResult();   
    }
}
