<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User_SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_SkillRepository extends EntityRepository
{
}
